[project]
name = "vla-rscl"
version = "0.1.0"
description = "reproducing RS-CL (contrastive regularization for VLAs) on LIBERO"
requires-python = ">=3.10"
dependencies = [
    "torch>=2.1",
    "torchvision>=0.16",
    "numpy",
    "h5py",
    "matplotlib",
    "pillow",
    "tqdm",
    "pyyaml",
    "termcolor",
    "huggingface-hub[cli]",
    "wandb",
    "transformers>=5.5.0",
    "tyro>=1.0.12",
    "dm-tree>=0.1.10",
]

[tool.setuptools.packages.find]
include = ["rscl*"]

[project.optional-dependencies]
sim = [
    "robosuite==1.4.0",
    "libero",
    "mujoco",
    "robomimic",
    "bddl",
]
dev = [
    "ipython",
    "ipykernel",
]
